# Generated by Django 4.2.14 on 2024-07-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='complated',
            field=models.BooleanField(default=False),
        ),
    ]
